export const AUTH_BASE_URL = "https://6ab1-169-255-4-18.ngrok.io";
export const CONFIG_BASE_URL = "http://localhost:56040";
export const GATEWAY = "http://localhost:56032"
export const LOGIN_URL = `${GATEWAY}/v1/user/login`;
export const REGISTER_URL = `${GATEWAY}/v1/user/register`;
export const WEB_CONFIG_URL = `${GATEWAY}/v1/config/menus`;
export const PREDICTION_URL = `${GATEWAY}/v1/game/predict`;
export const IMG_URL_BASE = 'https://raw.githubusercontent.com/Ngai-E/resources/main/';
// export const IMG_URL_BASE = 'https://github.com/Ngai-E/resources/blob/main/';
